/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
IF NOT EXISTS (SELECT TOP 1 * FROM Countries )
BEGIN
    INSERT INTO Countries VALUES ('Afghanistan');
    INSERT INTO Countries VALUES ('Albania');
    INSERT INTO Countries VALUES ('Algeria');
    INSERT INTO Countries VALUES ('American Samoa');
    INSERT INTO Countries VALUES ('Andorra');
    INSERT INTO Countries VALUES ('Angola');
    INSERT INTO Countries VALUES ('Anguilla');
    INSERT INTO Countries VALUES ('Antarctica');
    INSERT INTO Countries VALUES ('Antigua and Barbuda');
    INSERT INTO Countries VALUES ('Argentina');
    INSERT INTO Countries VALUES ('Armenia');
    INSERT INTO Countries VALUES ('Aruba');
    INSERT INTO Countries VALUES ('Australia');
    INSERT INTO Countries VALUES ('Austria');
    INSERT INTO Countries VALUES ('Azerbaijan');
    INSERT INTO Countries VALUES ('Bahamas');
    INSERT INTO Countries VALUES ('Bahrain');
    INSERT INTO Countries VALUES ('Bangladesh');
    INSERT INTO Countries VALUES ('Barbados');
    INSERT INTO Countries VALUES ('Belarus');
    INSERT INTO Countries VALUES ('Belgium');
    INSERT INTO Countries VALUES ('Belize');
    INSERT INTO Countries VALUES ('Benin');
    INSERT INTO Countries VALUES ('Bermuda');
    INSERT INTO Countries VALUES ('Bhutan');
    INSERT INTO Countries VALUES ('Bolivia');
    INSERT INTO Countries VALUES ('Bosnia and Herzegovina');
    INSERT INTO Countries VALUES ('Botswana');
    INSERT INTO Countries VALUES ('Bouvet Island');
    INSERT INTO Countries VALUES ('Brazil');
    INSERT INTO Countries VALUES ('British Indian Ocean Territory');
    INSERT INTO Countries VALUES ('Brunei Darussalam');
    INSERT INTO Countries VALUES ('Bulgaria');
    INSERT INTO Countries VALUES ('Burkina Faso');
    INSERT INTO Countries VALUES ('Burundi');
    INSERT INTO Countries VALUES ('Cambodia');
    INSERT INTO Countries VALUES ('Cameroon');
    INSERT INTO Countries VALUES ('Canada');
    INSERT INTO Countries VALUES ('Cape Verde');
    INSERT INTO Countries VALUES ('Cayman Islands');
    INSERT INTO Countries VALUES ('Central African Republic');
    INSERT INTO Countries VALUES ('Chad');
    INSERT INTO Countries VALUES ('Chile');
    INSERT INTO Countries VALUES ('China');
    INSERT INTO Countries VALUES ('Christmas Island');
    INSERT INTO Countries VALUES ('Cocos (Keeling) Islands');
    INSERT INTO Countries VALUES ('Colombia');
    INSERT INTO Countries VALUES ('Comoros');
    INSERT INTO Countries VALUES ('Democratic Republic of the Congo');
    INSERT INTO Countries VALUES ('Republic of Congo');
    INSERT INTO Countries VALUES ('Cook Islands');
    INSERT INTO Countries VALUES ('Costa Rica');
    INSERT INTO Countries VALUES ('Croatia (Hrvatska)');
    INSERT INTO Countries VALUES ('Cuba');
    INSERT INTO Countries VALUES ('Cyprus');
    INSERT INTO Countries VALUES ('Czech Republic');
    INSERT INTO Countries VALUES ('Denmark');
    INSERT INTO Countries VALUES ('Djibouti');
    INSERT INTO Countries VALUES ('Dominica');
    INSERT INTO Countries VALUES ('Dominican Republic');
    INSERT INTO Countries VALUES ('East Timor');
    INSERT INTO Countries VALUES ('Ecuador');
    INSERT INTO Countries VALUES ('Egypt');
    INSERT INTO Countries VALUES ('El Salvador');
    INSERT INTO Countries VALUES ('Equatorial Guinea');
    INSERT INTO Countries VALUES ('Eritrea');
    INSERT INTO Countries VALUES ('Estonia');
    INSERT INTO Countries VALUES ('Ethiopia');
    INSERT INTO Countries VALUES ('Falkland Islands (Malvinas)');
    INSERT INTO Countries VALUES ('Faroe Islands');
    INSERT INTO Countries VALUES ('Fiji');
    INSERT INTO Countries VALUES ('Finland');
    INSERT INTO Countries VALUES ('France');
    INSERT INTO Countries VALUES ('French Guiana');
    INSERT INTO Countries VALUES ('French Polynesia');
    INSERT INTO Countries VALUES ('French Southern Territories');
    INSERT INTO Countries VALUES ('Gabon');
    INSERT INTO Countries VALUES ('Gambia');
    INSERT INTO Countries VALUES ('Georgia');
    INSERT INTO Countries VALUES ('Germany');
    INSERT INTO Countries VALUES ('Ghana');
    INSERT INTO Countries VALUES ('Gibraltar');
    INSERT INTO Countries VALUES ('Guernsey');
    INSERT INTO Countries VALUES ('Greece');
    INSERT INTO Countries VALUES ('Greenland');
    INSERT INTO Countries VALUES ('Grenada');
    INSERT INTO Countries VALUES ('Guadeloupe');
    INSERT INTO Countries VALUES ('Guam');
    INSERT INTO Countries VALUES ('Guatemala');
    INSERT INTO Countries VALUES ('Guinea');
    INSERT INTO Countries VALUES ('Guinea-Bissau');
    INSERT INTO Countries VALUES ('Guyana');
    INSERT INTO Countries VALUES ('Haiti');
    INSERT INTO Countries VALUES ('Honduras');
    INSERT INTO Countries VALUES ('Hong Kong');
    INSERT INTO Countries VALUES ('Hungary');
    INSERT INTO Countries VALUES ('Iceland');
    INSERT INTO Countries VALUES ('India');
    INSERT INTO Countries VALUES ('Isle of Man');
    INSERT INTO Countries VALUES ('Indonesia');
    INSERT INTO Countries VALUES ('Iran');
    INSERT INTO Countries VALUES ('Iraq');
    INSERT INTO Countries VALUES ('Ireland');
    INSERT INTO Countries VALUES ('Israel');
    INSERT INTO Countries VALUES ('Italy');
    INSERT INTO Countries VALUES ('Ivory Coast');
    INSERT INTO Countries VALUES ('Jersey');
    INSERT INTO Countries VALUES ('Jamaica');
    INSERT INTO Countries VALUES ('Japan');
    INSERT INTO Countries VALUES ('Jordan');
    INSERT INTO Countries VALUES ('Kazakhstan');
    INSERT INTO Countries VALUES ('Kenya');
    INSERT INTO Countries VALUES ('Kiribati');
    INSERT INTO Countries VALUES ('Kosovo');
    INSERT INTO Countries VALUES ('Kuwait');
    INSERT INTO Countries VALUES ('Kyrgyzstan');
    INSERT INTO Countries VALUES ('Laos');
    INSERT INTO Countries VALUES ('Latvia');
    INSERT INTO Countries VALUES ('Lebanon');
    INSERT INTO Countries VALUES ('Lesotho');
    INSERT INTO Countries VALUES ('Liberia');
    INSERT INTO Countries VALUES ('Libya');
    INSERT INTO Countries VALUES ('Liechtenstein');
    INSERT INTO Countries VALUES ('Lithuania');
    INSERT INTO Countries VALUES ('Luxembourg');
    INSERT INTO Countries VALUES ('Macau');
    INSERT INTO Countries VALUES ('North Macedonia');
    INSERT INTO Countries VALUES ('Madagascar');
    INSERT INTO Countries VALUES ('Malawi');
    INSERT INTO Countries VALUES ('Malaysia');
    INSERT INTO Countries VALUES ('Maldives');
    INSERT INTO Countries VALUES ('Mali');
    INSERT INTO Countries VALUES ('Malta');
    INSERT INTO Countries VALUES ('Marshall Islands');
    INSERT INTO Countries VALUES ('Martinique');
    INSERT INTO Countries VALUES ('Mauritania');
    INSERT INTO Countries VALUES ('Mauritius');
    INSERT INTO Countries VALUES ('Mayotte');
    INSERT INTO Countries VALUES ('Mexico');
    INSERT INTO Countries VALUES ('Micronesia');
    INSERT INTO Countries VALUES ('Moldova');
    INSERT INTO Countries VALUES ('Monaco');
    INSERT INTO Countries VALUES ('Mongolia');
    INSERT INTO Countries VALUES ('Montenegro');
    INSERT INTO Countries VALUES ('Montserrat');
    INSERT INTO Countries VALUES ('Morocco');
    INSERT INTO Countries VALUES ('Mozambique');
    INSERT INTO Countries VALUES ('Myanmar');
    INSERT INTO Countries VALUES ('Namibia');
    INSERT INTO Countries VALUES ('Nauru');
    INSERT INTO Countries VALUES ('Nepal');
    INSERT INTO Countries VALUES ('Netherlands');
    INSERT INTO Countries VALUES ('Netherlands Antilles');
    INSERT INTO Countries VALUES ('New Caledonia');
    INSERT INTO Countries VALUES ('New Zealand');
    INSERT INTO Countries VALUES ('Nicaragua');
    INSERT INTO Countries VALUES ('Niger');
    INSERT INTO Countries VALUES ('Nigeria');
    INSERT INTO Countries VALUES ('Niue');
    INSERT INTO Countries VALUES ('Norfolk Island');
    INSERT INTO Countries VALUES ('Northern Mariana Islands');
    INSERT INTO Countries VALUES ('North Korea');
    INSERT INTO Countries VALUES ('Norway');
    INSERT INTO Countries VALUES ('Oman');
    INSERT INTO Countries VALUES ('Pakistan');
    INSERT INTO Countries VALUES ('Palau');
    INSERT INTO Countries VALUES ('Palestine');
    INSERT INTO Countries VALUES ('Panama');
    INSERT INTO Countries VALUES ('Papua New Guinea');
    INSERT INTO Countries VALUES ('Paraguay');
    INSERT INTO Countries VALUES ('Peru');
    INSERT INTO Countries VALUES ('Philippines');
    INSERT INTO Countries VALUES ('Pitcairn');
    INSERT INTO Countries VALUES ('Poland');
    INSERT INTO Countries VALUES ('Portugal');
    INSERT INTO Countries VALUES ('Puerto Rico');
    INSERT INTO Countries VALUES ('Qatar');
    INSERT INTO Countries VALUES ('Reunion');
    INSERT INTO Countries VALUES ('Romania');
    INSERT INTO Countries VALUES ('Russian Federation');
    INSERT INTO Countries VALUES ('Rwanda');
    INSERT INTO Countries VALUES ('Saint Kitts and Nevis');
    INSERT INTO Countries VALUES ('Saint Lucia');
    INSERT INTO Countries VALUES ('Saint Vincent and the Grenadines');
    INSERT INTO Countries VALUES ('Samoa');
    INSERT INTO Countries VALUES ('San Marino');
    INSERT INTO Countries VALUES ('Sao Tome and Principe');
    INSERT INTO Countries VALUES ('Saudi Arabia');
    INSERT INTO Countries VALUES ('Senegal');
    INSERT INTO Countries VALUES ('Serbia');
    INSERT INTO Countries VALUES ('Seychelles');
    INSERT INTO Countries VALUES ('Sierra Leone');
    INSERT INTO Countries VALUES ('Singapore');
    INSERT INTO Countries VALUES ('Slovakia');
    INSERT INTO Countries VALUES ('Slovenia');
    INSERT INTO Countries VALUES ('Solomon Islands');
    INSERT INTO Countries VALUES ('Somalia');
    INSERT INTO Countries VALUES ('South Africa');
    INSERT INTO Countries VALUES ('South Georgia South Sandwich Islands');
    INSERT INTO Countries VALUES ('South Korea');
    INSERT INTO Countries VALUES ('South Sudan');
    INSERT INTO Countries VALUES ('Spain');
    INSERT INTO Countries VALUES ('Sri Lanka');
    INSERT INTO Countries VALUES ('St. Helena');
    INSERT INTO Countries VALUES ('St. Pierre and Miquelon');
    INSERT INTO Countries VALUES ('Sudan');
    INSERT INTO Countries VALUES ('Suriname');
    INSERT INTO Countries VALUES ('Svalbard and Jan Mayen Islands');
    INSERT INTO Countries VALUES ('Swaziland');
    INSERT INTO Countries VALUES ('Sweden');
    INSERT INTO Countries VALUES ('Switzerland');
    INSERT INTO Countries VALUES ('Syria');
    INSERT INTO Countries VALUES ('Taiwan');
    INSERT INTO Countries VALUES ('Tajikistan');
    INSERT INTO Countries VALUES ('Tanzania');
    INSERT INTO Countries VALUES ('Thailand');
    INSERT INTO Countries VALUES ('Togo');
    INSERT INTO Countries VALUES ('Tokelau');
    INSERT INTO Countries VALUES ('Tonga');
    INSERT INTO Countries VALUES ('Trinidad and Tobago');
    INSERT INTO Countries VALUES ('Tunisia');
    INSERT INTO Countries VALUES ('Turkey');
    INSERT INTO Countries VALUES ('Turkmenistan');
    INSERT INTO Countries VALUES ('Turks and Caicos Islands');
    INSERT INTO Countries VALUES ('Tuvalu');
    INSERT INTO Countries VALUES ('Uganda');
    INSERT INTO Countries VALUES ('Ukraine');
    INSERT INTO Countries VALUES ('United Arab Emirates');
    INSERT INTO Countries VALUES ('United Kingdom');
    INSERT INTO Countries VALUES ('United States');
    INSERT INTO Countries VALUES ('Uruguay');
    INSERT INTO Countries VALUES ('Uzbekistan');
    INSERT INTO Countries VALUES ('Vanuatu');
    INSERT INTO Countries VALUES ('Vatican City State');
    INSERT INTO Countries VALUES ('Venezuela');
    INSERT INTO Countries VALUES ('Vietnam');
    INSERT INTO Countries VALUES ('Virgin Islands (British)');
    INSERT INTO Countries VALUES ('Virgin Islands (U.S.)');
    INSERT INTO Countries VALUES ('Wallis and Futuna Islands');
    INSERT INTO Countries VALUES ('Western Sahara');
    INSERT INTO Countries VALUES ('Yemen');
    INSERT INTO Countries VALUES ('Zambia');
    INSERT INTO Countries VALUES ('Zimbabwe');
END

IF NOT EXISTS (SELECT TOP 1 * FROM EmissionStandards )
BEGIN
   INSERT INTO EmissionStandards VALUES ('Euro 1');
   INSERT INTO EmissionStandards VALUES ('Euro 2');
   INSERT INTO EmissionStandards VALUES ('Euro 3');
   INSERT INTO EmissionStandards VALUES ('Euro 4');
   INSERT INTO EmissionStandards VALUES ('Euro 5a');
   INSERT INTO EmissionStandards VALUES ('Euro 5b');
   INSERT INTO EmissionStandards VALUES ('Euro 6b');
   INSERT INTO EmissionStandards VALUES ('Euro 6c');
   INSERT INTO EmissionStandards VALUES ('Euro 6d-Temp');
   INSERT INTO EmissionStandards VALUES ('Euro 6d');
END

IF NOT EXISTS (SELECT TOP 1 * FROM FuelTypes )
BEGIN
   INSERT INTO FuelTypes VALUES ('Gasoline');
   INSERT INTO FuelTypes VALUES ('Diesel');
   INSERT INTO FuelTypes VALUES ('Ethanol');
   INSERT INTO FuelTypes VALUES ('LPG');
   INSERT INTO FuelTypes VALUES ('Hydrogen');
END